# Generated by Django 6.0.4 on 2026-06-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_review_updated_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("reviewer_id", "reviewee_id", "job_id"),
                name="unique_review_per_job",
            ),
        ),
        migrations.AlterModelTable(
            name="review",
            table=None,
        ),
    ]
